
teracy-dev:
  # teracy-dev location specification
  location:
    git:
      remote:
        origin: https://github.com/teracyhq/dev.git
      branch: v0.6.0-a8
    sync: true

  # teracy-dev-entry auto update
  entry_location:
    git:
      remote:
        origin: https://github.com/teracyhq-incubator/teracy-dev-entry-v05.git
      branch: master
    sync: true

  extensions:
    # use teracy-dev-core v0.4.0
    - _id: "kernel-core"
      location:
        git:
          branch: v0.4.0
      require_version: ">= 0.4.0"

    - _id: "entry-essential"
      path:
        extension: teracy-dev-essential
      location:
        git:
          remote:
            origin: https://github.com/teracyhq-incubator/teracy-dev-essential.git
          branch: v0.3.0
      require_version: ">= 0.3.0"
      enabled: true

    - _id: "entry-v05-compat"
      path:
        extension: teracy-dev-v05-compat
      location:
        git:
          remote:
            origin: https://github.com/teracyhq-incubator/teracy-dev-v05-compat.git
          branch: v0.3.0
      require_version: ">= 0.3.0"
      enabled: true
